SELECT
    qh.DATABASE_NAME,
    qh.SCHEMA_NAME,
    SUM(qah.CREDITS_ATTRIBUTED_COMPUTE) AS CREDITS_USED
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY qh
JOIN SNOWFLAKE.ACCOUNT_USAGE.QUERY_ATTRIBUTION_HISTORY qah
    ON qh.QUERY_ID = qah.QUERY_ID
WHERE qh.START_TIME >= DATEADD('day', -30, CURRENT_TIMESTAMP())
GROUP BY 1,2
ORDER BY 3 DESC;