-- ============================================================
-- PHASE 2: ENVIRONMENT PREPARATION
-- ============================================================
-- Creates: Warehouse, Database, Schemas, Roles, Users, Grants
-- Runs as: ACCOUNTADMIN
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS AUTOPULSE_WH
    WITH WAREHOUSE_SIZE = 'X-SMALL' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE
    COMMENT = 'AutoPulse AI project warehouse';
ALTER WAREHOUSE AUTOPULSE_WH SET WAREHOUSE_SIZE = 'X-SMALL', AUTO_SUSPEND = 300, AUTO_RESUME = TRUE;
USE WAREHOUSE AUTOPULSE_WH;

-- Database + ownership
CREATE DATABASE IF NOT EXISTS AUTOPULSE_AI COMMENT = 'AutoPulse AI battery intelligence, DQ, ML and Cortex platform';
GRANT OWNERSHIP ON DATABASE AUTOPULSE_AI TO ROLE SYSADMIN COPY CURRENT GRANTS;

-- Schemas (as ACCOUNTADMIN since SYSADMIN may not have grants yet after clean slate)
CREATE SCHEMA IF NOT EXISTS AUTOPULSE_AI.RAW COMMENT = 'Raw ingestion layer';
CREATE SCHEMA IF NOT EXISTS AUTOPULSE_AI.CURATED COMMENT = 'Curated business layer';
CREATE SCHEMA IF NOT EXISTS AUTOPULSE_AI.DQ COMMENT = 'Data quality framework';
CREATE SCHEMA IF NOT EXISTS AUTOPULSE_AI.CLEAN COMMENT = 'Clean/standardized data layer';
CREATE SCHEMA IF NOT EXISTS AUTOPULSE_AI.OPS COMMENT = 'Operational metadata and tracking';

-- Roles
CREATE ROLE IF NOT EXISTS AUTOPULSE_COMMON COMMENT = 'Common AutoPulse access';
CREATE ROLE IF NOT EXISTS AUTOPULSE_ETL_ENGINEER COMMENT = 'ETL/Data Engineering';
CREATE ROLE IF NOT EXISTS AUTOPULSE_AI_ENGINEER COMMENT = 'AI Engineering';
CREATE ROLE IF NOT EXISTS AUTOPULSE_PYTHON_ENGINEER COMMENT = 'Python Engineering';
CREATE ROLE IF NOT EXISTS AUTOPULSE_VIEWER COMMENT = 'Read-only consumer/judge access';

-- Role hierarchy
GRANT ROLE AUTOPULSE_COMMON TO ROLE SYSADMIN;
GRANT ROLE AUTOPULSE_ETL_ENGINEER TO ROLE SYSADMIN;
GRANT ROLE AUTOPULSE_AI_ENGINEER TO ROLE SYSADMIN;
GRANT ROLE AUTOPULSE_PYTHON_ENGINEER TO ROLE SYSADMIN;
GRANT ROLE AUTOPULSE_VIEWER TO ROLE SYSADMIN;

-- COMMON grants
GRANT USAGE ON DATABASE AUTOPULSE_AI TO ROLE AUTOPULSE_COMMON;
GRANT USAGE ON ALL SCHEMAS IN DATABASE AUTOPULSE_AI TO ROLE AUTOPULSE_COMMON;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE AUTOPULSE_AI TO ROLE AUTOPULSE_COMMON;
GRANT USAGE ON WAREHOUSE AUTOPULSE_WH TO ROLE AUTOPULSE_COMMON;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AUTOPULSE_AI.CURATED TO ROLE AUTOPULSE_COMMON;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA AUTOPULSE_AI.CURATED TO ROLE AUTOPULSE_COMMON;

-- VIEWER grants
GRANT USAGE ON DATABASE AUTOPULSE_AI TO ROLE AUTOPULSE_VIEWER;
GRANT USAGE ON SCHEMA AUTOPULSE_AI.CURATED TO ROLE AUTOPULSE_VIEWER;
GRANT USAGE ON WAREHOUSE AUTOPULSE_WH TO ROLE AUTOPULSE_VIEWER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AUTOPULSE_AI.CURATED TO ROLE AUTOPULSE_VIEWER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA AUTOPULSE_AI.CURATED TO ROLE AUTOPULSE_VIEWER;
GRANT USAGE ON FUTURE STREAMLITS IN SCHEMA AUTOPULSE_AI.CURATED TO ROLE AUTOPULSE_VIEWER;

-- ETL ENGINEER grants
GRANT USAGE ON DATABASE AUTOPULSE_AI TO ROLE AUTOPULSE_ETL_ENGINEER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE AUTOPULSE_AI TO ROLE AUTOPULSE_ETL_ENGINEER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE AUTOPULSE_AI TO ROLE AUTOPULSE_ETL_ENGINEER;
GRANT USAGE, OPERATE, MONITOR ON WAREHOUSE AUTOPULSE_WH TO ROLE AUTOPULSE_ETL_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT, CREATE PIPE, CREATE STREAM, CREATE PROCEDURE, CREATE FUNCTION ON SCHEMA AUTOPULSE_AI.RAW TO ROLE AUTOPULSE_ETL_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA AUTOPULSE_AI.RAW TO ROLE AUTOPULSE_ETL_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW, CREATE STREAM, CREATE TASK, CREATE PROCEDURE, CREATE FUNCTION ON SCHEMA AUTOPULSE_AI.DQ TO ROLE AUTOPULSE_ETL_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA AUTOPULSE_AI.DQ TO ROLE AUTOPULSE_ETL_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA AUTOPULSE_AI.CLEAN TO ROLE AUTOPULSE_ETL_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA AUTOPULSE_AI.CLEAN TO ROLE AUTOPULSE_ETL_ENGINEER;
GRANT CREATE TABLE, CREATE VIEW, CREATE DYNAMIC TABLE, CREATE STREAM ON SCHEMA AUTOPULSE_AI.CURATED TO ROLE AUTOPULSE_ETL_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA AUTOPULSE_AI.CURATED TO ROLE AUTOPULSE_ETL_ENGINEER;
GRANT CREATE TABLE, CREATE PROCEDURE ON SCHEMA AUTOPULSE_AI.OPS TO ROLE AUTOPULSE_ETL_ENGINEER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA AUTOPULSE_AI.OPS TO ROLE AUTOPULSE_ETL_ENGINEER;
GRANT EXECUTE TASK ON ACCOUNT TO ROLE AUTOPULSE_ETL_ENGINEER;
GRANT EXECUTE MANAGED TASK ON ACCOUNT TO ROLE AUTOPULSE_ETL_ENGINEER;

-- AI ENGINEER grants
GRANT USAGE ON DATABASE AUTOPULSE_AI TO ROLE AUTOPULSE_AI_ENGINEER;
GRANT USAGE ON SCHEMA AUTOPULSE_AI.CURATED TO ROLE AUTOPULSE_AI_ENGINEER;
GRANT USAGE ON SCHEMA AUTOPULSE_AI.DQ TO ROLE AUTOPULSE_AI_ENGINEER;
GRANT USAGE ON SCHEMA AUTOPULSE_AI.OPS TO ROLE AUTOPULSE_AI_ENGINEER;
GRANT USAGE ON WAREHOUSE AUTOPULSE_WH TO ROLE AUTOPULSE_AI_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AUTOPULSE_AI.CURATED TO ROLE AUTOPULSE_AI_ENGINEER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA AUTOPULSE_AI.CURATED TO ROLE AUTOPULSE_AI_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AUTOPULSE_AI.DQ TO ROLE AUTOPULSE_AI_ENGINEER;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE AUTOPULSE_AI_ENGINEER;
GRANT CREATE AGENT ON SCHEMA AUTOPULSE_AI.CURATED TO ROLE AUTOPULSE_AI_ENGINEER;
GRANT CREATE SEMANTIC VIEW ON SCHEMA AUTOPULSE_AI.CURATED TO ROLE AUTOPULSE_AI_ENGINEER;
GRANT CREATE CORTEX SEARCH SERVICE ON SCHEMA AUTOPULSE_AI.CURATED TO ROLE AUTOPULSE_AI_ENGINEER;
GRANT CREATE STREAMLIT ON SCHEMA AUTOPULSE_AI.CURATED TO ROLE AUTOPULSE_AI_ENGINEER;

-- PYTHON ENGINEER grants
GRANT USAGE ON DATABASE AUTOPULSE_AI TO ROLE AUTOPULSE_PYTHON_ENGINEER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE AUTOPULSE_AI TO ROLE AUTOPULSE_PYTHON_ENGINEER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE AUTOPULSE_AI TO ROLE AUTOPULSE_PYTHON_ENGINEER;
GRANT USAGE ON WAREHOUSE AUTOPULSE_WH TO ROLE AUTOPULSE_PYTHON_ENGINEER;
GRANT CREATE PROCEDURE, CREATE FUNCTION, CREATE STREAM, CREATE MODEL ON SCHEMA AUTOPULSE_AI.CLEAN TO ROLE AUTOPULSE_PYTHON_ENGINEER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AUTOPULSE_AI.CURATED TO ROLE AUTOPULSE_PYTHON_ENGINEER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA AUTOPULSE_AI.CURATED TO ROLE AUTOPULSE_PYTHON_ENGINEER;
GRANT CREATE STREAMLIT ON SCHEMA AUTOPULSE_AI.CURATED TO ROLE AUTOPULSE_PYTHON_ENGINEER;

-- Users
SET TEMP_PASSWORD = 'TempPassword@123';

CREATE USER IF NOT EXISTS SHAREENKHAN
    PASSWORD = $TEMP_PASSWORD LOGIN_NAME = 'shareen_khan' DISPLAY_NAME = 'Shareen Khan'
    FIRST_NAME = 'Shareen' LAST_NAME = 'Khan' EMAIL = 'shareen.khan@capgemini.com'
    DEFAULT_ROLE = AUTOPULSE_AI_ENGINEER DEFAULT_WAREHOUSE = AUTOPULSE_WH MUST_CHANGE_PASSWORD = TRUE;

CREATE USER IF NOT EXISTS PRASHANTPALIWAL
    PASSWORD = $TEMP_PASSWORD LOGIN_NAME = 'prashant.paliwal' DISPLAY_NAME = 'Prashant Paliwal'
    FIRST_NAME = 'Prashant' LAST_NAME = 'Paliwal' EMAIL = 'prashant.paliwal@capgemini.com'
    DEFAULT_ROLE = AUTOPULSE_ETL_ENGINEER DEFAULT_WAREHOUSE = AUTOPULSE_WH MUST_CHANGE_PASSWORD = TRUE;

CREATE USER IF NOT EXISTS VEERESHGODUGU
    PASSWORD = $TEMP_PASSWORD LOGIN_NAME = 'godugu.veeresh' DISPLAY_NAME = 'Veeresh Godugu'
    FIRST_NAME = 'Veeresh' LAST_NAME = 'Godugu' EMAIL = 'godugu.veeresh@capgemini.com'
    DEFAULT_ROLE = AUTOPULSE_PYTHON_ENGINEER DEFAULT_WAREHOUSE = AUTOPULSE_WH MUST_CHANGE_PASSWORD = TRUE;

GRANT ROLE AUTOPULSE_COMMON TO USER SHAREENKHAN;
GRANT ROLE AUTOPULSE_AI_ENGINEER TO USER SHAREENKHAN;
GRANT ROLE AUTOPULSE_COMMON TO USER PRASHANTPALIWAL;
GRANT ROLE AUTOPULSE_ETL_ENGINEER TO USER PRASHANTPALIWAL;
GRANT ROLE AUTOPULSE_COMMON TO USER VEERESHGODUGU;
GRANT ROLE AUTOPULSE_PYTHON_ENGINEER TO USER VEERESHGODUGU;
