-- ============================================================
-- PHASE 3: DEPLOYMENT EXECUTION
-- ============================================================
-- Creates all data objects: RAW tables, CLEAN tables, DQ framework,
-- Curated dynamic tables, OPS cost layer.
--
-- NOTE: This phased script runs as ACCOUNTADMIN for speed and
-- simplicity during EXECUTE IMMEDIATE deployment. The standalone
-- layer scripts (03_raw_layer/, 04_clean_layer/, etc.) use
-- SYSADMIN for granular RBAC when run individually.
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE AUTOPULSE_WH;
USE DATABASE AUTOPULSE_AI;


-- ============================================================
-- 3A. RAW LAYER — File Format + Stage + 11 Tables
-- ============================================================

CREATE FILE FORMAT IF NOT EXISTS AUTOPULSE_AI.RAW.CSV_FILE_FORMAT
    TYPE = CSV SKIP_HEADER = 1 FIELD_DELIMITER = ',' TRIM_SPACE = TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY = '"' EMPTY_FIELD_AS_NULL = TRUE NULL_IF = ('NULL', 'null', '');

CREATE STAGE IF NOT EXISTS AUTOPULSE_AI.RAW.AUTOPULSE_RAW_STAGE
    FILE_FORMAT = (FORMAT_NAME = 'AUTOPULSE_AI.RAW.CSV_FILE_FORMAT');

CREATE TABLE IF NOT EXISTS AUTOPULSE_AI.RAW.BATTERY_COMPONENTS_RAW (BATTERY_TYPE NUMBER(1,0), ANODE VARCHAR, CATHODE VARCHAR, ELECTROLYTE VARCHAR, SOURCE_FILE_NAME VARCHAR(500), LOAD_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE TABLE IF NOT EXISTS AUTOPULSE_AI.RAW.BATTERY_SUPPLIER_RAW (ID NUMBER(2,0), NAME VARCHAR, SOURCE_FILE_NAME VARCHAR(500), LOAD_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE TABLE IF NOT EXISTS AUTOPULSE_AI.RAW.BATTERY_TYPE_RAW (ID NUMBER(2,0), NAME VARCHAR, SOURCE_FILE_NAME VARCHAR(500), LOAD_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE TABLE IF NOT EXISTS AUTOPULSE_AI.RAW.DATE_VALUES_YEAR_RAW (DATE_VALUE DATE, YEAR_VALUE NUMBER(4,0), SOURCE_FILE_NAME VARCHAR(500), LOAD_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE TABLE IF NOT EXISTS AUTOPULSE_AI.RAW.DTC_BATTERY_ERROR_CODES_RAW (ERROR_ID VARCHAR, ERROR_CODE VARCHAR, DESCRIPTION VARCHAR, SOURCE_FILE_NAME VARCHAR(500), LOAD_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE TABLE IF NOT EXISTS AUTOPULSE_AI.RAW.PART_BATTERY_RAW (PART_ID NUMBER(10,0), PART_NUMBER VARCHAR, TYPE NUMBER(2,0), AH NUMBER(10,2), AMP_HOURS VARCHAR, TERMINAL VARCHAR, SIZE_LENGTH_CM NUMBER(10,2), SUPPLIER NUMBER(2,0), MFG_YEAR NUMBER(4,0), TEMP_RANGE_CELSIUS VARCHAR, TEMP_RANGE_FAHRENHEIT VARCHAR, VOLTAGE_RANGE VARCHAR, RECOMMENDED_CHARGING_VOLTAGE_RANGE VARCHAR, RECOMMENDED_CHARGING_CURRENT_RANGE VARCHAR, OVERCHARGE_PROTECTION VARCHAR, OVERCURRENT_PROTECTION VARCHAR, DISCHARGE_CURRENT VARCHAR, CUT_OFF_VOLTAGE VARCHAR, SOURCE_FILE_NAME VARCHAR(500), LOAD_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE TABLE IF NOT EXISTS AUTOPULSE_AI.RAW.STATES_AND_ABBREVIATIONS_RAW (STATE VARCHAR, ABBREVIATION VARCHAR, SOURCE_FILE_NAME VARCHAR(500), LOAD_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE TABLE IF NOT EXISTS AUTOPULSE_AI.RAW.VEHICLES_RAW (CAR_ID NUMBER(10,0), VIN VARCHAR, MODEL_YEAR NUMBER(4,0), VEHICLE_CONFIG VARCHAR, DOORS NUMBER(1,0), STATE VARCHAR, STATE_AB VARCHAR, COUNTRY VARCHAR, PART_NUMBER VARCHAR, BATTERY_SERIAL_NUMBER VARCHAR, SOURCE_FILE_NAME VARCHAR(500), LOAD_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE TABLE IF NOT EXISTS AUTOPULSE_AI.RAW.VEHICLE_EVENTS_RAW (CAR_ID NUMBER(10,0), VIN VARCHAR, MODEL_YEAR NUMBER(4,0), VEHICLE_CONFIG VARCHAR, DOORS NUMBER(1,0), STATE VARCHAR, STATE_AB VARCHAR, CITY VARCHAR, COUNTRY VARCHAR, ZIP VARCHAR, LONGITUDE NUMBER(15,6), LATITUDE NUMBER(15,6), DES_LONG NUMBER(15,6), DEST_LAT NUMBER(15,6), DIST_IN_M NUMBER(15,2), PART_NUMBER VARCHAR, BATTERY_SERIAL_NUMBER VARCHAR, DATE_VALUES DATE, AVG_TEMP_F NUMBER(10,2), AVG_WIND_SPEED_MPH NUMBER(10,2), TOT_PRECIPITATION_IN NUMBER(10,4), TOT_SNOWFALL_IN NUMBER(10,4), DTC_ERROR_CODE NUMBER(2,0), SOURCE_FILE_NAME VARCHAR(500), LOAD_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE TABLE IF NOT EXISTS AUTOPULSE_AI.RAW.WEATHER_DATA_RAW (DATE_VALUE DATE, AVG_TEMP_F NUMBER(10,2), AVG_WIND_SPEED_MPH NUMBER(10,2), TOT_PRECIPITATION_IN NUMBER(10,4), TOT_SNOWFALL_IN NUMBER(10,4), SOURCE_FILE_NAME VARCHAR(500), LOAD_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE TABLE IF NOT EXISTS AUTOPULSE_AI.RAW.ZIP_CODE_INFO_RAW (ZIP VARCHAR, CITY VARCHAR, STATE VARCHAR, LATITUDE NUMBER(15,6), LONGITUDE NUMBER(15,6), SOURCE_FILE_NAME VARCHAR(500), LOAD_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());


-- ============================================================
-- 3B. RAW LAYER — 11 Pipes
-- ============================================================

CREATE OR REPLACE PIPE AUTOPULSE_AI.RAW.PIPE_BATTERY_COMPONENTS AUTO_INGEST = TRUE AS COPY INTO AUTOPULSE_AI.RAW.BATTERY_COMPONENTS_RAW (BATTERY_TYPE,ANODE,CATHODE,ELECTROLYTE,SOURCE_FILE_NAME,LOAD_TIMESTAMP) FROM (SELECT $1,$2,$3,$4,METADATA$FILENAME,CURRENT_TIMESTAMP() FROM @AUTOPULSE_AI.RAW.AUTOPULSE_RAW_STAGE/) FILE_FORMAT=(FORMAT_NAME='AUTOPULSE_AI.RAW.CSV_FILE_FORMAT') PATTERN='.*BATTERY_COMPONENTS[.]csv';
CREATE OR REPLACE PIPE AUTOPULSE_AI.RAW.PIPE_BATTERY_SUPPLIER AUTO_INGEST = TRUE AS COPY INTO AUTOPULSE_AI.RAW.BATTERY_SUPPLIER_RAW (ID,NAME,SOURCE_FILE_NAME,LOAD_TIMESTAMP) FROM (SELECT $1,$2,METADATA$FILENAME,CURRENT_TIMESTAMP() FROM @AUTOPULSE_AI.RAW.AUTOPULSE_RAW_STAGE/) FILE_FORMAT=(FORMAT_NAME='AUTOPULSE_AI.RAW.CSV_FILE_FORMAT') PATTERN='.*BATTERY_SUPPLIER[.]csv';
CREATE OR REPLACE PIPE AUTOPULSE_AI.RAW.PIPE_BATTERY_TYPE AUTO_INGEST = TRUE AS COPY INTO AUTOPULSE_AI.RAW.BATTERY_TYPE_RAW (ID,NAME,SOURCE_FILE_NAME,LOAD_TIMESTAMP) FROM (SELECT $1,$2,METADATA$FILENAME,CURRENT_TIMESTAMP() FROM @AUTOPULSE_AI.RAW.AUTOPULSE_RAW_STAGE/) FILE_FORMAT=(FORMAT_NAME='AUTOPULSE_AI.RAW.CSV_FILE_FORMAT') PATTERN='.*BATTERY_TYPE[.]csv';
CREATE OR REPLACE PIPE AUTOPULSE_AI.RAW.PIPE_DATE_VALUES_YEAR AUTO_INGEST = TRUE AS COPY INTO AUTOPULSE_AI.RAW.DATE_VALUES_YEAR_RAW (DATE_VALUE,YEAR_VALUE,SOURCE_FILE_NAME,LOAD_TIMESTAMP) FROM (SELECT $1,$2,METADATA$FILENAME,CURRENT_TIMESTAMP() FROM @AUTOPULSE_AI.RAW.AUTOPULSE_RAW_STAGE/) FILE_FORMAT=(FORMAT_NAME='AUTOPULSE_AI.RAW.CSV_FILE_FORMAT') PATTERN='.*DATE_VALUES_YEAR[.]csv';
CREATE OR REPLACE PIPE AUTOPULSE_AI.RAW.PIPE_DTC_BATTERY_ERROR_CODES AUTO_INGEST = TRUE AS COPY INTO AUTOPULSE_AI.RAW.DTC_BATTERY_ERROR_CODES_RAW (ERROR_ID,ERROR_CODE,DESCRIPTION,SOURCE_FILE_NAME,LOAD_TIMESTAMP) FROM (SELECT $1,$2,$3,METADATA$FILENAME,CURRENT_TIMESTAMP() FROM @AUTOPULSE_AI.RAW.AUTOPULSE_RAW_STAGE/) FILE_FORMAT=(FORMAT_NAME='AUTOPULSE_AI.RAW.CSV_FILE_FORMAT') PATTERN='.*DTC_BATTERY_ERROR_CODES[.]csv';
CREATE OR REPLACE PIPE AUTOPULSE_AI.RAW.PIPE_PART_BATTERY AUTO_INGEST = TRUE AS COPY INTO AUTOPULSE_AI.RAW.PART_BATTERY_RAW (PART_ID,AH,AMP_HOURS,TERMINAL,SIZE_LENGTH_CM,MFG_YEAR,PART_NUMBER,TYPE,SUPPLIER,TEMP_RANGE_CELSIUS,TEMP_RANGE_FAHRENHEIT,VOLTAGE_RANGE,RECOMMENDED_CHARGING_VOLTAGE_RANGE,RECOMMENDED_CHARGING_CURRENT_RANGE,OVERCHARGE_PROTECTION,OVERCURRENT_PROTECTION,DISCHARGE_CURRENT,CUT_OFF_VOLTAGE,SOURCE_FILE_NAME,LOAD_TIMESTAMP) FROM (SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,METADATA$FILENAME,CURRENT_TIMESTAMP() FROM @AUTOPULSE_AI.RAW.AUTOPULSE_RAW_STAGE/) FILE_FORMAT=(FORMAT_NAME='AUTOPULSE_AI.RAW.CSV_FILE_FORMAT') PATTERN='.*PART_BATTERY[.]csv';
CREATE OR REPLACE PIPE AUTOPULSE_AI.RAW.PIPE_STATES_AND_ABBREVIATIONS AUTO_INGEST = TRUE AS COPY INTO AUTOPULSE_AI.RAW.STATES_AND_ABBREVIATIONS_RAW (STATE,ABBREVIATION,SOURCE_FILE_NAME,LOAD_TIMESTAMP) FROM (SELECT $1,$2,METADATA$FILENAME,CURRENT_TIMESTAMP() FROM @AUTOPULSE_AI.RAW.AUTOPULSE_RAW_STAGE/) FILE_FORMAT=(FORMAT_NAME='AUTOPULSE_AI.RAW.CSV_FILE_FORMAT') PATTERN='.*STATES_AND_ABBREVIATIONS[.]csv';
CREATE OR REPLACE PIPE AUTOPULSE_AI.RAW.PIPE_VEHICLES AUTO_INGEST = TRUE AS COPY INTO AUTOPULSE_AI.RAW.VEHICLES_RAW (CAR_ID,VIN,MODEL_YEAR,VEHICLE_CONFIG,DOORS,STATE,STATE_AB,COUNTRY,PART_NUMBER,BATTERY_SERIAL_NUMBER,SOURCE_FILE_NAME,LOAD_TIMESTAMP) FROM (SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,METADATA$FILENAME,CURRENT_TIMESTAMP() FROM @AUTOPULSE_AI.RAW.AUTOPULSE_RAW_STAGE/) FILE_FORMAT=(FORMAT_NAME='AUTOPULSE_AI.RAW.CSV_FILE_FORMAT') PATTERN='.*[/]VEHICLES[.]csv';
CREATE OR REPLACE PIPE AUTOPULSE_AI.RAW.PIPE_VEHICLE_EVENTS AUTO_INGEST = TRUE AS COPY INTO AUTOPULSE_AI.RAW.VEHICLE_EVENTS_RAW (CAR_ID,VIN,MODEL_YEAR,VEHICLE_CONFIG,DOORS,STATE,STATE_AB,CITY,COUNTRY,PART_NUMBER,BATTERY_SERIAL_NUMBER,ZIP,LONGITUDE,LATITUDE,DES_LONG,DEST_LAT,DIST_IN_M,DATE_VALUES,AVG_TEMP_F,AVG_WIND_SPEED_MPH,TOT_PRECIPITATION_IN,TOT_SNOWFALL_IN,DTC_ERROR_CODE,SOURCE_FILE_NAME,LOAD_TIMESTAMP) FROM (SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$19,$20,$21,$22,$23,$24,METADATA$FILENAME,CURRENT_TIMESTAMP() FROM @AUTOPULSE_AI.RAW.AUTOPULSE_RAW_STAGE/) FILE_FORMAT=(FORMAT_NAME='AUTOPULSE_AI.RAW.CSV_FILE_FORMAT') PATTERN='.*VEHICLES_ZIPCODES_DISTANCES_DATES_WEATHER_DTC.*[.]csv';
CREATE OR REPLACE PIPE AUTOPULSE_AI.RAW.PIPE_WEATHER_DATA AUTO_INGEST = TRUE AS COPY INTO AUTOPULSE_AI.RAW.WEATHER_DATA_RAW (DATE_VALUE,AVG_TEMP_F,AVG_WIND_SPEED_MPH,TOT_PRECIPITATION_IN,TOT_SNOWFALL_IN,SOURCE_FILE_NAME,LOAD_TIMESTAMP) FROM (SELECT $2,$3,$4,$5,$6,METADATA$FILENAME,CURRENT_TIMESTAMP() FROM @AUTOPULSE_AI.RAW.AUTOPULSE_RAW_STAGE/) FILE_FORMAT=(FORMAT_NAME='AUTOPULSE_AI.RAW.CSV_FILE_FORMAT') PATTERN='.*WEATHER_DATA[.]csv';
CREATE OR REPLACE PIPE AUTOPULSE_AI.RAW.PIPE_ZIP_CODE_INFO AUTO_INGEST = TRUE AS COPY INTO AUTOPULSE_AI.RAW.ZIP_CODE_INFO_RAW (ZIP,CITY,STATE,LATITUDE,LONGITUDE,SOURCE_FILE_NAME,LOAD_TIMESTAMP) FROM (SELECT $1,$2,$3,$4,$5,METADATA$FILENAME,CURRENT_TIMESTAMP() FROM @AUTOPULSE_AI.RAW.AUTOPULSE_RAW_STAGE/) FILE_FORMAT=(FORMAT_NAME='AUTOPULSE_AI.RAW.CSV_FILE_FORMAT') PATTERN='.*ZIP_CODE_INFO[.]csv';


-- ============================================================
-- 3C. CLEAN LAYER — 11 Tables
-- ============================================================

CREATE OR REPLACE TABLE AUTOPULSE_AI.CLEAN.BATTERY_COMPONENTS_CLEAN (BATTERY_TYPE NUMBER(1,0), ANODE VARCHAR, CATHODE VARCHAR, ELECTROLYTE VARCHAR, SOURCE_FILE_NAME VARCHAR(500), LOAD_TIMESTAMP TIMESTAMP_NTZ(9));
CREATE OR REPLACE TABLE AUTOPULSE_AI.CLEAN.BATTERY_SUPPLIER_CLEAN (ID NUMBER(1,0), NAME VARCHAR, STATE VARCHAR, LATITUDE NUMBER(6,4), LONGITUDE NUMBER(7,4), SOURCE_FILE_NAME VARCHAR(500), LOAD_TIMESTAMP TIMESTAMP_NTZ(9));
CREATE OR REPLACE TABLE AUTOPULSE_AI.CLEAN.BATTERY_TYPE_CLEAN (ID NUMBER(1,0), NAME VARCHAR, SOURCE_FILE_NAME VARCHAR(500), LOAD_TIMESTAMP TIMESTAMP_NTZ(9));
CREATE OR REPLACE TABLE AUTOPULSE_AI.CLEAN.DATE_VALUES_YEAR_CLEAN (DATE_VALUES DATE, YEAR NUMBER(4,0), SOURCE_FILE_NAME VARCHAR(500), LOAD_TIMESTAMP TIMESTAMP_NTZ(9));
CREATE OR REPLACE TABLE AUTOPULSE_AI.CLEAN.DTC_BATTERY_ERROR_CODES_CLEAN (ERROR_ID NUMBER(1,0), ERROR_CODE VARCHAR, DESCRIPTION VARCHAR, SOURCE_FILE_NAME VARCHAR(500), LOAD_TIMESTAMP TIMESTAMP_NTZ(9));
CREATE OR REPLACE TABLE AUTOPULSE_AI.CLEAN.PART_BATTERY_CLEAN (PART_ID NUMBER(3,0), AH NUMBER(3,0), AMP_HOURS VARCHAR, TERMINAL VARCHAR, SIZE_LENGTH_CM NUMBER(2,0), MFG_YEAR NUMBER(4,0), PART_NUMBER VARCHAR, TYPE NUMBER(1,0), SUPPLIER NUMBER(1,0), TEMP_RANGE_CELSIUS VARCHAR, TEMP_RANGE_FAHRENHEIT VARCHAR, VOLTAGE_RANGE VARCHAR, RECOMMENDED_CHARGING_VOLTAGE_RANGE VARCHAR, RECOMMENDED_CHARGING_CURRENT_RANGE VARCHAR, OVERCHARGE_PROTECTION NUMBER(1,0), OVERCURRENT_PROTECTION NUMBER(1,0), DISCHARGE_CURRENT VARCHAR, CUT_OFF_VOLTAGE VARCHAR, SOURCE_FILE_NAME VARCHAR(500), LOAD_TIMESTAMP TIMESTAMP_NTZ(9));
CREATE OR REPLACE TABLE AUTOPULSE_AI.CLEAN.STATES_AND_ABBREVIATIONS_CLEAN (ID NUMBER(2,0), STATE VARCHAR, STATE_AB VARCHAR, SOURCE_FILE_NAME VARCHAR(500), LOAD_TIMESTAMP TIMESTAMP_NTZ(9));
CREATE OR REPLACE TABLE AUTOPULSE_AI.CLEAN.VEHICLES_CLEAN (CAR_ID NUMBER(5,0), VIN VARCHAR, MODEL_YEAR NUMBER(4,0), VEHICLE_CONFIG VARCHAR, DOORS NUMBER(1,0), STATE VARCHAR, STATE_AB VARCHAR, COUNTRY VARCHAR, PART_NUMBER VARCHAR, BATTERY_SERIAL_NUMBER VARCHAR, SOURCE_FILE_NAME VARCHAR(500), LOAD_TIMESTAMP TIMESTAMP_NTZ(9));
CREATE OR REPLACE TABLE AUTOPULSE_AI.CLEAN.VEHICLE_EVENTS_CLEAN (CAR_ID NUMBER(4,0), VIN VARCHAR, MODEL_YEAR NUMBER(4,0), VEHICLE_CONFIG VARCHAR, DOORS NUMBER(1,0), STATE VARCHAR, STATE_AB VARCHAR, CITY VARCHAR, COUNTRY VARCHAR, PART_NUMBER VARCHAR, BATTERY_SERIAL_NUMBER VARCHAR, ZIP NUMBER(5,0), LONGITUDE NUMBER(8,6), LATITUDE NUMBER(8,6), DES_LONG NUMBER(8,6), DEST_LAT NUMBER(8,6), DIST_IN_M NUMBER(5,2), RECORD_COUNTS NUMBER(3,0), DATE_VALUES DATE, AVG_TEMP_F NUMBER(3,1), AVG_WIND_SPEED_MPH NUMBER(3,1), TOT_PRECIPITATION_IN NUMBER(3,2), TOT_SNOWFALL_IN NUMBER(3,2), DTC_ERROR_CODE NUMBER(1,0), SOURCE_FILE_NAME VARCHAR(500), LOAD_TIMESTAMP TIMESTAMP_NTZ(9));
CREATE OR REPLACE TABLE AUTOPULSE_AI.CLEAN.WEATHER_DATA_CLEAN (POSTAL_CODE VARCHAR, DATE_VALID_STD DATE, AVG_TEMPERATURE_AIR_2M_F NUMBER(4,1), AVG_WIND_SPEED_10M_MPH NUMBER(3,1), TOT_PRECIPITATION_IN NUMBER(4,2), TOT_SNOWFALL_IN NUMBER(4,2), SOURCE_FILE_NAME VARCHAR(500), LOAD_TIMESTAMP TIMESTAMP_NTZ(9));
CREATE OR REPLACE TABLE AUTOPULSE_AI.CLEAN.ZIP_CODE_INFO_CLEAN (ZIP VARCHAR(5), LATITUDE NUMBER(17,15), LONGITUDE NUMBER(9,6), CITY VARCHAR, STATE VARCHAR, SOURCE_FILE_NAME VARCHAR(500), LOAD_TIMESTAMP TIMESTAMP_NTZ(9));


-- ============================================================
-- 3D. DQ FRAMEWORK — Tables + UDF + Streams + Tasks
-- ============================================================

-- DQ tables
CREATE TABLE IF NOT EXISTS AUTOPULSE_AI.DQ.DQ_RULES (RULE_ID VARCHAR(100), RULE_NAME VARCHAR(200), SOURCE_TABLE VARCHAR(200), RULE_TYPE VARCHAR(50), IS_ACTIVE BOOLEAN DEFAULT TRUE, SOURCE_COLUMN VARCHAR(200), RULE_SQL VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(), UPDATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(), CREATED_BY VARCHAR(200), COMMENT VARCHAR(16777216));
CREATE TABLE IF NOT EXISTS AUTOPULSE_AI.DQ.DQ_RESULTS (DQ_RESULT_ID VARCHAR(100), RUN_ID VARCHAR(100), RULE_ID VARCHAR(100), SOURCE_TABLE VARCHAR(200), SOURCE_COLUMN VARCHAR(200), CHECKED_AT TIMESTAMP_NTZ(9), ROWS_CHECKED NUMBER(38,0), ROWS_PASSED NUMBER(38,0), ROWS_FAILED NUMBER(38,0), STATUS VARCHAR(20), FAILURE_PERCENTAGE NUMBER(7,4), FAILURE_SUMMARY VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());
CREATE TABLE IF NOT EXISTS AUTOPULSE_AI.DQ.REJECTED_RECORDS (REJECTED_RECORD_ID VARCHAR(100) DEFAULT UUID_STRING(), RUN_ID VARCHAR(100), SOURCE_FILE_NAME VARCHAR(500), SOURCE_TABLE VARCHAR(200), SOURCE_ROW_NUMBER NUMBER(38,0), RECORD_KEY VARCHAR(500), RECORD_DATA VARIANT, RULE_ID VARCHAR(100), RULE_NAME VARCHAR(200), REJECTION_REASON VARCHAR(16777216), REJECTED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(), REPROCESS_STATUS VARCHAR(30) DEFAULT 'PENDING', REPROCESS_ATTEMPTS NUMBER(10,0) DEFAULT 0, REPROCESSED_AT TIMESTAMP_NTZ(9), REPROCESS_NOTES VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());

-- OPS table
CREATE TABLE IF NOT EXISTS AUTOPULSE_AI.OPS.PIPELINE_RUNS (RUN_ID VARCHAR(100), SOURCE_TABLE VARCHAR(200), STARTED_AT TIMESTAMP_NTZ(9), COMPLETED_AT TIMESTAMP_NTZ(9), STATUS VARCHAR(20), ROWS_INGESTED NUMBER(38,0), ROWS_PASSED NUMBER(38,0), ROWS_FAILED NUMBER(38,0), ROWS_LOADED NUMBER(38,0), ERROR_MESSAGE VARCHAR(16777216), CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP());

-- DQ UDF
CREATE OR REPLACE FUNCTION AUTOPULSE_AI.DQ.NORMALIZE_EVENT_DATE(P_DATE DATE) RETURNS DATE LANGUAGE SQL AS $$ CASE WHEN P_DATE IS NULL THEN NULL WHEN YEAR(P_DATE) BETWEEN 0 AND 99 THEN DATE_FROM_PARTS(YEAR(P_DATE)+2000, MONTH(P_DATE), DAY(P_DATE)) ELSE P_DATE END $$;

-- 11 DQ Streams
CREATE OR REPLACE STREAM AUTOPULSE_AI.DQ.STREAM_BATTERY_COMPONENTS_RAW ON TABLE AUTOPULSE_AI.RAW.BATTERY_COMPONENTS_RAW APPEND_ONLY=TRUE;
CREATE OR REPLACE STREAM AUTOPULSE_AI.DQ.STREAM_BATTERY_SUPPLIER_RAW ON TABLE AUTOPULSE_AI.RAW.BATTERY_SUPPLIER_RAW APPEND_ONLY=TRUE;
CREATE OR REPLACE STREAM AUTOPULSE_AI.DQ.STREAM_BATTERY_TYPE_RAW ON TABLE AUTOPULSE_AI.RAW.BATTERY_TYPE_RAW APPEND_ONLY=TRUE;
CREATE OR REPLACE STREAM AUTOPULSE_AI.DQ.STREAM_DATE_VALUES_YEAR_RAW ON TABLE AUTOPULSE_AI.RAW.DATE_VALUES_YEAR_RAW APPEND_ONLY=TRUE;
CREATE OR REPLACE STREAM AUTOPULSE_AI.DQ.STREAM_DTC_BATTERY_ERROR_CODES_RAW ON TABLE AUTOPULSE_AI.RAW.DTC_BATTERY_ERROR_CODES_RAW APPEND_ONLY=TRUE;
CREATE OR REPLACE STREAM AUTOPULSE_AI.DQ.STREAM_PART_BATTERY_RAW ON TABLE AUTOPULSE_AI.RAW.PART_BATTERY_RAW APPEND_ONLY=TRUE;
CREATE OR REPLACE STREAM AUTOPULSE_AI.DQ.STREAM_STATES_AND_ABBREVIATIONS_RAW ON TABLE AUTOPULSE_AI.RAW.STATES_AND_ABBREVIATIONS_RAW APPEND_ONLY=TRUE;
CREATE OR REPLACE STREAM AUTOPULSE_AI.DQ.STREAM_VEHICLES_RAW ON TABLE AUTOPULSE_AI.RAW.VEHICLES_RAW APPEND_ONLY=TRUE;
CREATE OR REPLACE STREAM AUTOPULSE_AI.DQ.STREAM_VEHICLE_EVENTS_RAW ON TABLE AUTOPULSE_AI.RAW.VEHICLE_EVENTS_RAW APPEND_ONLY=TRUE;
CREATE OR REPLACE STREAM AUTOPULSE_AI.DQ.STREAM_WEATHER_DATA_RAW ON TABLE AUTOPULSE_AI.RAW.WEATHER_DATA_RAW APPEND_ONLY=TRUE;
CREATE OR REPLACE STREAM AUTOPULSE_AI.DQ.STREAM_ZIP_CODE_INFO_RAW ON TABLE AUTOPULSE_AI.RAW.ZIP_CODE_INFO_RAW APPEND_ONLY=TRUE;

-- 11 DQ Tasks (DEMO: 1 MINUTE)
CREATE OR REPLACE TASK AUTOPULSE_AI.DQ.TASK_DQ_BATTERY_COMPONENTS USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE='XSMALL' SCHEDULE='1 MINUTE' WHEN SYSTEM$STREAM_HAS_DATA('AUTOPULSE_AI.DQ.STREAM_BATTERY_COMPONENTS_RAW') AS CALL AUTOPULSE_AI.DQ.RUN_DQ_FW('BATTERY_COMPONENTS_RAW');
CREATE OR REPLACE TASK AUTOPULSE_AI.DQ.TASK_DQ_BATTERY_SUPPLIER USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE='XSMALL' SCHEDULE='1 MINUTE' WHEN SYSTEM$STREAM_HAS_DATA('AUTOPULSE_AI.DQ.STREAM_BATTERY_SUPPLIER_RAW') AS CALL AUTOPULSE_AI.DQ.RUN_DQ_FW('BATTERY_SUPPLIER_RAW');
CREATE OR REPLACE TASK AUTOPULSE_AI.DQ.TASK_DQ_BATTERY_TYPE USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE='XSMALL' SCHEDULE='1 MINUTE' WHEN SYSTEM$STREAM_HAS_DATA('AUTOPULSE_AI.DQ.STREAM_BATTERY_TYPE_RAW') AS CALL AUTOPULSE_AI.DQ.RUN_DQ_FW('BATTERY_TYPE_RAW');
CREATE OR REPLACE TASK AUTOPULSE_AI.DQ.TASK_DQ_DATE_VALUES_YEAR USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE='XSMALL' SCHEDULE='1 MINUTE' WHEN SYSTEM$STREAM_HAS_DATA('AUTOPULSE_AI.DQ.STREAM_DATE_VALUES_YEAR_RAW') AS CALL AUTOPULSE_AI.DQ.RUN_DQ_FW('DATE_VALUES_YEAR_RAW');
CREATE OR REPLACE TASK AUTOPULSE_AI.DQ.TASK_DQ_DTC_BATTERY_ERROR_CODES USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE='XSMALL' SCHEDULE='1 MINUTE' WHEN SYSTEM$STREAM_HAS_DATA('AUTOPULSE_AI.DQ.STREAM_DTC_BATTERY_ERROR_CODES_RAW') AS CALL AUTOPULSE_AI.DQ.RUN_DQ_FW('DTC_BATTERY_ERROR_CODES_RAW');
CREATE OR REPLACE TASK AUTOPULSE_AI.DQ.TASK_DQ_PART_BATTERY USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE='XSMALL' SCHEDULE='1 MINUTE' WHEN SYSTEM$STREAM_HAS_DATA('AUTOPULSE_AI.DQ.STREAM_PART_BATTERY_RAW') AS CALL AUTOPULSE_AI.DQ.RUN_DQ_FW('PART_BATTERY_RAW');
CREATE OR REPLACE TASK AUTOPULSE_AI.DQ.TASK_DQ_STATES_AND_ABBREVIATIONS USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE='XSMALL' SCHEDULE='1 MINUTE' WHEN SYSTEM$STREAM_HAS_DATA('AUTOPULSE_AI.DQ.STREAM_STATES_AND_ABBREVIATIONS_RAW') AS CALL AUTOPULSE_AI.DQ.RUN_DQ_FW('STATES_AND_ABBREVIATIONS_RAW');
CREATE OR REPLACE TASK AUTOPULSE_AI.DQ.TASK_DQ_VEHICLES USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE='XSMALL' SCHEDULE='1 MINUTE' WHEN SYSTEM$STREAM_HAS_DATA('AUTOPULSE_AI.DQ.STREAM_VEHICLES_RAW') AS CALL AUTOPULSE_AI.DQ.RUN_DQ_FW('VEHICLES_RAW');
CREATE OR REPLACE TASK AUTOPULSE_AI.DQ.TASK_DQ_VEHICLE_EVENTS USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE='XSMALL' SCHEDULE='1 MINUTE' WHEN SYSTEM$STREAM_HAS_DATA('AUTOPULSE_AI.DQ.STREAM_VEHICLE_EVENTS_RAW') AS CALL AUTOPULSE_AI.DQ.RUN_DQ_FW('VEHICLE_EVENTS_RAW');
CREATE OR REPLACE TASK AUTOPULSE_AI.DQ.TASK_DQ_WEATHER_DATA USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE='XSMALL' SCHEDULE='1 MINUTE' WHEN SYSTEM$STREAM_HAS_DATA('AUTOPULSE_AI.DQ.STREAM_WEATHER_DATA_RAW') AS CALL AUTOPULSE_AI.DQ.RUN_DQ_FW('WEATHER_DATA_RAW');
CREATE OR REPLACE TASK AUTOPULSE_AI.DQ.TASK_DQ_ZIP_CODE_INFO USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE='XSMALL' SCHEDULE='1 MINUTE' WHEN SYSTEM$STREAM_HAS_DATA('AUTOPULSE_AI.DQ.STREAM_ZIP_CODE_INFO_RAW') AS CALL AUTOPULSE_AI.DQ.RUN_DQ_FW('ZIP_CODE_INFO_RAW');

-- Resume all tasks
ALTER TASK AUTOPULSE_AI.DQ.TASK_DQ_BATTERY_COMPONENTS RESUME;
ALTER TASK AUTOPULSE_AI.DQ.TASK_DQ_BATTERY_SUPPLIER RESUME;
ALTER TASK AUTOPULSE_AI.DQ.TASK_DQ_BATTERY_TYPE RESUME;
ALTER TASK AUTOPULSE_AI.DQ.TASK_DQ_DATE_VALUES_YEAR RESUME;
ALTER TASK AUTOPULSE_AI.DQ.TASK_DQ_DTC_BATTERY_ERROR_CODES RESUME;
ALTER TASK AUTOPULSE_AI.DQ.TASK_DQ_PART_BATTERY RESUME;
ALTER TASK AUTOPULSE_AI.DQ.TASK_DQ_STATES_AND_ABBREVIATIONS RESUME;
ALTER TASK AUTOPULSE_AI.DQ.TASK_DQ_VEHICLES RESUME;
ALTER TASK AUTOPULSE_AI.DQ.TASK_DQ_VEHICLE_EVENTS RESUME;
ALTER TASK AUTOPULSE_AI.DQ.TASK_DQ_WEATHER_DATA RESUME;
ALTER TASK AUTOPULSE_AI.DQ.TASK_DQ_ZIP_CODE_INFO RESUME;


-- ============================================================
-- 3E. OPS LAYER — 6 Cost Tables + Procedure + Task
-- ============================================================

CREATE TABLE IF NOT EXISTS AUTOPULSE_AI.OPS.COST_WAREHOUSE (WAREHOUSE_NAME VARCHAR, USAGE_DATE TIMESTAMP_LTZ, CREDITS_USED NUMBER(38,9), CREDITS_COMPUTE NUMBER(38,9), CREDITS_CLOUD NUMBER(38,9));
CREATE TABLE IF NOT EXISTS AUTOPULSE_AI.OPS.COST_SERVERLESS (TASK_NAME VARCHAR, TASK_SCHEMA VARCHAR, USAGE_DATE TIMESTAMP_LTZ, CREDITS_USED NUMBER(38,9));
CREATE TABLE IF NOT EXISTS AUTOPULSE_AI.OPS.COST_PIPES (PIPE_NAME VARCHAR, USAGE_DATE TIMESTAMP_LTZ, CREDITS_USED NUMBER(38,9), BYTES_INSERTED NUMBER(38,0), FILES_INSERTED NUMBER(38,0));
CREATE TABLE IF NOT EXISTS AUTOPULSE_AI.OPS.COST_STORAGE (USAGE_DATE DATE, STORAGE_TB NUMBER(20,4), STAGE_TB NUMBER(20,4), FAILSAFE_TB NUMBER(20,4), TOTAL_TB NUMBER(20,4));
CREATE TABLE IF NOT EXISTS AUTOPULSE_AI.OPS.COST_STREAMLIT_RUNTIME (USAGE_DATE DATE, START_TIME TIMESTAMP_LTZ, END_TIME TIMESTAMP_LTZ, COMPUTE_POOL_NAME VARCHAR, RUNTIME_TYPE VARCHAR, CREDITS_USED NUMBER(38,9));
CREATE TABLE IF NOT EXISTS AUTOPULSE_AI.OPS.COST_STREAMLIT_DDL (USAGE_DATE DATE, DDL_TYPE VARCHAR, USER_NAME VARCHAR, ROLE_NAME VARCHAR, WAREHOUSE_NAME VARCHAR, STATEMENT_COUNT NUMBER(38,0));
