-- ============================================================
-- ROLLBACK SCRIPT — AutoPulse AI
-- ============================================================
-- Use this to selectively roll back specific layers without
-- destroying the entire project. For full teardown, use
-- 05_teardown.sql instead.
--
-- Usage: Uncomment the section(s) you want to roll back.
-- ============================================================

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE AUTOPULSE_WH;


-- ============================================================
-- ROLLBACK LEVEL 1: Agents only
-- Removes all 6 Cortex Agents. Semantic views remain.
-- ============================================================

-- DROP AGENT IF EXISTS AUTOPULSE_AI.CURATED.AUTOPULSE_BATTERY_AGENT;
-- DROP AGENT IF EXISTS AUTOPULSE_AI.CURATED.AUTOPULSE_DQ_INTELLIGENCE;
-- DROP AGENT IF EXISTS AUTOPULSE_AI.CURATED.AUTOPULSE_RCA_AGENT;
-- DROP AGENT IF EXISTS AUTOPULSE_AI.CURATED.AUTOPULSE_PREDICTIVE_AGENT;
-- DROP AGENT IF EXISTS AUTOPULSE_AI.CURATED.AUTOPULSE_OPS_AGENT;
-- DROP AGENT IF EXISTS AUTOPULSE_AI.CURATED.AUTOPULSE_VEHICLE_QUALITY_AGENT;


-- ============================================================
-- ROLLBACK LEVEL 2: Semantic Views
-- Removes all 3 semantic views. Agents will break.
-- ============================================================

-- DROP SEMANTIC VIEW IF EXISTS AUTOPULSE_AI.CURATED.AUTOPULSE_BATTERY_INTELLIGENCE;
-- DROP SEMANTIC VIEW IF EXISTS AUTOPULSE_AI.DQ.AUTOPULSE_DQ_INTELLIGENCE;
-- DROP SEMANTIC VIEW IF EXISTS AUTOPULSE_AI.OPS.AUTOPULSE_OPS_INTELLIGENCE;


-- ============================================================
-- ROLLBACK LEVEL 3: Curated Dynamic Tables
-- Removes all 5 DTs. Semantic views + agents will break.
-- ============================================================

-- ALTER DYNAMIC TABLE AUTOPULSE_AI.CURATED.VEHICLE_QUALITY_SCORECARD SUSPEND;
-- ALTER DYNAMIC TABLE AUTOPULSE_AI.CURATED.VEHICLE_BATTERY_PREDICTION SUSPEND;
-- ALTER DYNAMIC TABLE AUTOPULSE_AI.CURATED.VEHICLE_BATTERY_RCA SUSPEND;
-- ALTER DYNAMIC TABLE AUTOPULSE_AI.CURATED.VEHICLE_EVENT_CONTEXT SUSPEND;
-- ALTER DYNAMIC TABLE AUTOPULSE_AI.CURATED.VEHICLE_BATTERY_360 SUSPEND;

-- DROP DYNAMIC TABLE IF EXISTS AUTOPULSE_AI.CURATED.VEHICLE_QUALITY_SCORECARD;
-- DROP DYNAMIC TABLE IF EXISTS AUTOPULSE_AI.CURATED.VEHICLE_BATTERY_PREDICTION;
-- DROP DYNAMIC TABLE IF EXISTS AUTOPULSE_AI.CURATED.VEHICLE_BATTERY_RCA;
-- DROP DYNAMIC TABLE IF EXISTS AUTOPULSE_AI.CURATED.VEHICLE_EVENT_CONTEXT;
-- DROP DYNAMIC TABLE IF EXISTS AUTOPULSE_AI.CURATED.VEHICLE_BATTERY_360;


-- ============================================================
-- ROLLBACK LEVEL 4: OPS Cost Layer
-- Removes OPS tables + task. Dashboard OPS page uses
-- ACCOUNT_USAGE directly, so it still works.
-- ============================================================

-- ALTER TASK IF EXISTS AUTOPULSE_AI.OPS.OPS_COST_REFRESH_TASK SUSPEND;
-- DROP TASK IF EXISTS AUTOPULSE_AI.OPS.OPS_COST_REFRESH_TASK;
-- DROP PROCEDURE IF EXISTS AUTOPULSE_AI.OPS.OPS_COST_REFRESH();
-- DROP TABLE IF EXISTS AUTOPULSE_AI.OPS.COST_WAREHOUSE;
-- DROP TABLE IF EXISTS AUTOPULSE_AI.OPS.COST_SERVERLESS;
-- DROP TABLE IF EXISTS AUTOPULSE_AI.OPS.COST_PIPES;
-- DROP TABLE IF EXISTS AUTOPULSE_AI.OPS.COST_STORAGE;
-- DROP TABLE IF EXISTS AUTOPULSE_AI.OPS.COST_STREAMLIT_RUNTIME;
-- DROP TABLE IF EXISTS AUTOPULSE_AI.OPS.COST_STREAMLIT_DDL;


-- ============================================================
-- ROLLBACK LEVEL 5: DQ Framework (Tasks + Streams + Procedure)
-- Stops all DQ processing. CLEAN tables stop receiving data.
-- ============================================================

-- Suspend tasks first
-- ALTER TASK IF EXISTS AUTOPULSE_AI.DQ.TASK_DQ_BATTERY_COMPONENTS SUSPEND;
-- ALTER TASK IF EXISTS AUTOPULSE_AI.DQ.TASK_DQ_BATTERY_SUPPLIER SUSPEND;
-- ALTER TASK IF EXISTS AUTOPULSE_AI.DQ.TASK_DQ_BATTERY_TYPE SUSPEND;
-- ALTER TASK IF EXISTS AUTOPULSE_AI.DQ.TASK_DQ_DATE_VALUES_YEAR SUSPEND;
-- ALTER TASK IF EXISTS AUTOPULSE_AI.DQ.TASK_DQ_DTC_BATTERY_ERROR_CODES SUSPEND;
-- ALTER TASK IF EXISTS AUTOPULSE_AI.DQ.TASK_DQ_PART_BATTERY SUSPEND;
-- ALTER TASK IF EXISTS AUTOPULSE_AI.DQ.TASK_DQ_STATES_AND_ABBREVIATIONS SUSPEND;
-- ALTER TASK IF EXISTS AUTOPULSE_AI.DQ.TASK_DQ_VEHICLES SUSPEND;
-- ALTER TASK IF EXISTS AUTOPULSE_AI.DQ.TASK_DQ_VEHICLE_EVENTS SUSPEND;
-- ALTER TASK IF EXISTS AUTOPULSE_AI.DQ.TASK_DQ_WEATHER_DATA SUSPEND;
-- ALTER TASK IF EXISTS AUTOPULSE_AI.DQ.TASK_DQ_ZIP_CODE_INFO SUSPEND;

-- Then drop tasks
-- DROP TASK IF EXISTS AUTOPULSE_AI.DQ.TASK_DQ_BATTERY_COMPONENTS;
-- DROP TASK IF EXISTS AUTOPULSE_AI.DQ.TASK_DQ_BATTERY_SUPPLIER;
-- DROP TASK IF EXISTS AUTOPULSE_AI.DQ.TASK_DQ_BATTERY_TYPE;
-- DROP TASK IF EXISTS AUTOPULSE_AI.DQ.TASK_DQ_DATE_VALUES_YEAR;
-- DROP TASK IF EXISTS AUTOPULSE_AI.DQ.TASK_DQ_DTC_BATTERY_ERROR_CODES;
-- DROP TASK IF EXISTS AUTOPULSE_AI.DQ.TASK_DQ_PART_BATTERY;
-- DROP TASK IF EXISTS AUTOPULSE_AI.DQ.TASK_DQ_STATES_AND_ABBREVIATIONS;
-- DROP TASK IF EXISTS AUTOPULSE_AI.DQ.TASK_DQ_VEHICLES;
-- DROP TASK IF EXISTS AUTOPULSE_AI.DQ.TASK_DQ_VEHICLE_EVENTS;
-- DROP TASK IF EXISTS AUTOPULSE_AI.DQ.TASK_DQ_WEATHER_DATA;
-- DROP TASK IF EXISTS AUTOPULSE_AI.DQ.TASK_DQ_ZIP_CODE_INFO;

-- Drop streams
-- DROP STREAM IF EXISTS AUTOPULSE_AI.DQ.STREAM_BATTERY_COMPONENTS_RAW;
-- DROP STREAM IF EXISTS AUTOPULSE_AI.DQ.STREAM_BATTERY_SUPPLIER_RAW;
-- DROP STREAM IF EXISTS AUTOPULSE_AI.DQ.STREAM_BATTERY_TYPE_RAW;
-- DROP STREAM IF EXISTS AUTOPULSE_AI.DQ.STREAM_DATE_VALUES_YEAR_RAW;
-- DROP STREAM IF EXISTS AUTOPULSE_AI.DQ.STREAM_DTC_BATTERY_ERROR_CODES_RAW;
-- DROP STREAM IF EXISTS AUTOPULSE_AI.DQ.STREAM_PART_BATTERY_RAW;
-- DROP STREAM IF EXISTS AUTOPULSE_AI.DQ.STREAM_STATES_AND_ABBREVIATIONS_RAW;
-- DROP STREAM IF EXISTS AUTOPULSE_AI.DQ.STREAM_VEHICLES_RAW;
-- DROP STREAM IF EXISTS AUTOPULSE_AI.DQ.STREAM_VEHICLE_EVENTS_RAW;
-- DROP STREAM IF EXISTS AUTOPULSE_AI.DQ.STREAM_WEATHER_DATA_RAW;
-- DROP STREAM IF EXISTS AUTOPULSE_AI.DQ.STREAM_ZIP_CODE_INFO_RAW;

-- Drop procedure + UDF
-- DROP PROCEDURE IF EXISTS AUTOPULSE_AI.DQ.RUN_DQ_FW(VARCHAR);
-- DROP FUNCTION IF EXISTS AUTOPULSE_AI.DQ.NORMALIZE_EVENT_DATE(DATE);

-- Drop DQ tables (data loss!)
-- DROP TABLE IF EXISTS AUTOPULSE_AI.DQ.DQ_RULES;
-- DROP TABLE IF EXISTS AUTOPULSE_AI.DQ.DQ_RESULTS;
-- DROP TABLE IF EXISTS AUTOPULSE_AI.DQ.REJECTED_RECORDS;


-- ============================================================
-- ROLLBACK LEVEL 6: RAW Pipes
-- Stops all ingestion. Existing RAW data remains.
-- ============================================================

-- DROP PIPE IF EXISTS AUTOPULSE_AI.RAW.PIPE_BATTERY_COMPONENTS;
-- DROP PIPE IF EXISTS AUTOPULSE_AI.RAW.PIPE_BATTERY_SUPPLIER;
-- DROP PIPE IF EXISTS AUTOPULSE_AI.RAW.PIPE_BATTERY_TYPE;
-- DROP PIPE IF EXISTS AUTOPULSE_AI.RAW.PIPE_DATE_VALUES_YEAR;
-- DROP PIPE IF EXISTS AUTOPULSE_AI.RAW.PIPE_DTC_BATTERY_ERROR_CODES;
-- DROP PIPE IF EXISTS AUTOPULSE_AI.RAW.PIPE_PART_BATTERY;
-- DROP PIPE IF EXISTS AUTOPULSE_AI.RAW.PIPE_STATES_AND_ABBREVIATIONS;
-- DROP PIPE IF EXISTS AUTOPULSE_AI.RAW.PIPE_VEHICLES;
-- DROP PIPE IF EXISTS AUTOPULSE_AI.RAW.PIPE_VEHICLE_EVENTS;
-- DROP PIPE IF EXISTS AUTOPULSE_AI.RAW.PIPE_WEATHER_DATA;
-- DROP PIPE IF EXISTS AUTOPULSE_AI.RAW.PIPE_ZIP_CODE_INFO;


-- ============================================================
-- ROLLBACK LEVEL 7: Full Teardown
-- Use 05_teardown.sql instead — it drops DB, WH, roles, users.
-- ============================================================
